name: testliotast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install    dependencies
        run:    npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: cypress/results
